tap "homebrew/bundle"
tap "homebrew/php"
tap "caskroom/cask"

brew "ansiweather"
brew "aspell"
brew "docker"
brew "elinks"
brew "elixir"
brew "erlang"
brew "ffmpeg"
brew "go"
brew "graphviz"
brew "groovy"
brew "homebrew/php/php56"
brew "httperf"
brew "hub"
brew "imagemagick"
brew "jq"
brew "mono"
brew "node"
brew "p7zip"
brew "parallel"
brew "phantomjs"
brew "pigz"
brew "redis"
brew "rename"
brew "rlwrap" # Readline Wrapper
brew "rust"
brew "scala"
brew "the_silver_searcher"
brew "wget"
brew "xz"

cask "mojibar"
